-- MySQL Script generated by MySQL Workbench
-- Wed Jan 13 15:20:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema goodfood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema goodfood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `goodfood` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `goodfood` ;

-- -----------------------------------------------------
-- Table `goodfood`.`Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Adresse` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `pays` VARCHAR(45) NOT NULL,
  `codePostal` VARCHAR(6) NOT NULL,
  `rue` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `complement` VARCHAR(255) NULL,
  PRIMARY KEY (`idAdresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Franchise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Franchise` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Franchise` (
  `idFranchise` INT NOT NULL,
  `designation` VARCHAR(45) NOT NULL,
  `idAdresse` INT NULL,
  PRIMARY KEY (`idFranchise`),
  INDEX `fk_Franchise_Adresse1_idx` (`idAdresse` ASC) VISIBLE,
  CONSTRAINT `fk_Franchise_Adresse1`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `goodfood`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Utilisateur` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  `dateNaissance` DATETIME NULL,
  `email` VARCHAR(255) NULL,
  `telephoneMobile` VARCHAR(10) NULL,
  `telephoneFixe` VARCHAR(10) NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Employe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Employe` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Employe` (
  `idEmploye` INT NOT NULL,
  `idFranchise` INT NOT NULL,
  `nom` VARCHAR(255) NULL,
  `prenom` VARCHAR(255) NULL,
  `telephoneMobile` VARCHAR(10) NULL,
  `email` VARCHAR(255) NULL,
  PRIMARY KEY (`idEmploye`),
  INDEX `fk_Employe_Franchise1_idx` (`idFranchise` ASC) VISIBLE,
  CONSTRAINT `fk_Employe_Franchise1`
    FOREIGN KEY (`idFranchise`)
    REFERENCES `goodfood`.`Franchise` (`idFranchise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Statut`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Statut` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Statut` (
  `idStatut` INT NOT NULL,
  `designation` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idStatut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Commande` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Commande` (
  `idCommande` INT NOT NULL,
  `idFranchise` INT NOT NULL,
  `idStatut` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  `dateCreation` DATETIME NOT NULL,
  `idAdresseFacturation` INT NULL,
  `idAdresseLivraison` INT NULL,
  `dateDonnee` DATETIME NULL,
  PRIMARY KEY (`idCommande`),
  INDEX `fk_Commande_Franchise1_idx` (`idFranchise` ASC) VISIBLE,
  INDEX `fk_Commande_CommandeStatut1_idx` (`idStatut` ASC) VISIBLE,
  INDEX `fk_Commande_Utilisateur1_idx` (`idUtilisateur` ASC) VISIBLE,
  INDEX `fk_Commande_Adresse1_idx` (`idAdresseFacturation` ASC) VISIBLE,
  INDEX `fk_Commande_Adresse2_idx` (`idAdresseLivraison` ASC) VISIBLE,
  CONSTRAINT `fk_Commande_Franchise1`
    FOREIGN KEY (`idFranchise`)
    REFERENCES `goodfood`.`Franchise` (`idFranchise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_CommandeStatut1`
    FOREIGN KEY (`idStatut`)
    REFERENCES `goodfood`.`Statut` (`idStatut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `goodfood`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Adresse1`
    FOREIGN KEY (`idAdresseFacturation`)
    REFERENCES `goodfood`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Adresse2`
    FOREIGN KEY (`idAdresseLivraison`)
    REFERENCES `goodfood`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Formule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Formule` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Formule` (
  `idFormule` INT NOT NULL,
  `designation` VARCHAR(45) NOT NULL,
  `prix` INT NOT NULL,
  PRIMARY KEY (`idFormule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Produit` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Produit` (
  `idProduit` INT NOT NULL,
  `prix` INT NOT NULL,
  PRIMARY KEY (`idProduit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Categorie` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Categorie` (
  `idCategorie` INT NOT NULL,
  `designation` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Requiert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Requiert` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Requiert` (
  `idCategorie` INT NOT NULL,
  `idFormule` INT NOT NULL,
  `quantite` INT NOT NULL,
  PRIMARY KEY (`idCategorie`, `idFormule`),
  INDEX `fk_TypeProduit_has_Formule_Formule1_idx` (`idFormule` ASC) VISIBLE,
  INDEX `fk_TypeProduit_has_Formule_TypeProduit1_idx` (`idCategorie` ASC) VISIBLE,
  CONSTRAINT `fk_TypeProduit_has_Formule_TypeProduit1`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `goodfood`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TypeProduit_has_Formule_Formule1`
    FOREIGN KEY (`idFormule`)
    REFERENCES `goodfood`.`Formule` (`idFormule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Propose`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Propose` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Propose` (
  `idFranchise` INT NOT NULL,
  `idFormule` INT NOT NULL,
  `prix` INT NOT NULL,
  PRIMARY KEY (`idFranchise`, `idFormule`),
  INDEX `fk_Franchise_has_Formule_Formule1_idx` (`idFormule` ASC) VISIBLE,
  INDEX `fk_Franchise_has_Formule_Franchise1_idx` (`idFranchise` ASC) VISIBLE,
  CONSTRAINT `fk_Franchise_has_Formule_Franchise1`
    FOREIGN KEY (`idFranchise`)
    REFERENCES `goodfood`.`Franchise` (`idFranchise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Franchise_has_Formule_Formule1`
    FOREIGN KEY (`idFormule`)
    REFERENCES `goodfood`.`Formule` (`idFormule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Privilege`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Privilege` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Privilege` (
  `idPrivilege` INT NOT NULL,
  `designation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPrivilege`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Ingredient` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Ingredient` (
  `idIngredient` INT NOT NULL,
  `designation` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idIngredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`MvtEnt_StockHisto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`MvtEnt_StockHisto` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`MvtEnt_StockHisto` (
  `idMvtEnt_StockHisto` INT NOT NULL,
  `quantite` INT NULL,
  `date` DATETIME NULL,
  `Ingredient_idIngredient` INT NOT NULL,
  PRIMARY KEY (`idMvtEnt_StockHisto`, `Ingredient_idIngredient`),
  INDEX `fk_MvtEnt_StockHisto_Ingredient1_idx` (`Ingredient_idIngredient` ASC) VISIBLE,
  CONSTRAINT `fk_MvtEnt_StockHisto_Ingredient1`
    FOREIGN KEY (`Ingredient_idIngredient`)
    REFERENCES `goodfood`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`MvtSor_StockHisto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`MvtSor_StockHisto` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`MvtSor_StockHisto` (
  `idMvtSor_StockHisto` INT NOT NULL,
  `quantite` INT NULL,
  `date` DATETIME NULL,
  `Ingredient_idIngredient` INT NOT NULL,
  PRIMARY KEY (`idMvtSor_StockHisto`, `Ingredient_idIngredient`),
  INDEX `fk_MvtSor_StockHisto_Ingredient1_idx` (`Ingredient_idIngredient` ASC) VISIBLE,
  CONSTRAINT `fk_MvtSor_StockHisto_Ingredient1`
    FOREIGN KEY (`Ingredient_idIngredient`)
    REFERENCES `goodfood`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Stock` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Stock` (
  `idStock` INT NOT NULL,
  `quantite` INT NULL,
  `idIngredient` INT NOT NULL,
  PRIMARY KEY (`idStock`, `idIngredient`),
  INDEX `fk_Stock_Ingredient1_idx` (`idIngredient` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_Ingredient1`
    FOREIGN KEY (`idIngredient`)
    REFERENCES `goodfood`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Compose`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Compose` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Compose` (
  `idProduit` INT NOT NULL,
  `idIngredient` INT NOT NULL,
  `quantite` INT NOT NULL,
  PRIMARY KEY (`idProduit`, `idIngredient`),
  INDEX `fk_Produit_has_Ingredient_Ingredient1_idx` (`idIngredient` ASC) VISIBLE,
  INDEX `fk_Produit_has_Ingredient_Produit1_idx` (`idProduit` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_has_Ingredient_Produit1`
    FOREIGN KEY (`idProduit`)
    REFERENCES `goodfood`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_has_Ingredient_Ingredient1`
    FOREIGN KEY (`idIngredient`)
    REFERENCES `goodfood`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Composition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Composition` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Composition` (
  `idCommande` INT NOT NULL,
  `idFormule` INT NOT NULL,
  `idProduit` INT NOT NULL,
  `quantite` INT NOT NULL,
  PRIMARY KEY (`idCommande`, `idFormule`, `idProduit`),
  INDEX `fk_Commande_has_Formule (plateau repas)_Formule (plateau re_idx` (`idFormule` ASC) VISIBLE,
  INDEX `fk_Commande_has_Formule (plateau repas)_Commande1_idx` (`idCommande` ASC) VISIBLE,
  INDEX `fk_Composition_Produit1_idx` (`idProduit` ASC) VISIBLE,
  CONSTRAINT `fk_Commande_has_Formule (plateau repas)_Commande1`
    FOREIGN KEY (`idCommande`)
    REFERENCES `goodfood`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_Formule (plateau repas)_Formule (plateau repa1`
    FOREIGN KEY (`idFormule`)
    REFERENCES `goodfood`.`Formule` (`idFormule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Composition_Produit1`
    FOREIGN KEY (`idProduit`)
    REFERENCES `goodfood`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Commandee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Commandee` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Commandee` (
  `idCommande` INT NOT NULL,
  `idProduit` INT NOT NULL,
  `quantite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCommande`, `idProduit`),
  INDEX `fk_Commande_has_Produit_Produit1_idx` (`idProduit` ASC) VISIBLE,
  INDEX `fk_Commande_has_Produit_Commande1_idx` (`idCommande` ASC) VISIBLE,
  CONSTRAINT `fk_Commande_has_Produit_Commande1`
    FOREIGN KEY (`idCommande`)
    REFERENCES `goodfood`.`Commande` (`idCommande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_has_Produit_Produit1`
    FOREIGN KEY (`idProduit`)
    REFERENCES `goodfood`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Possede`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Possede` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Possede` (
  `idPrivilege` INT NOT NULL,
  `idEmploye` INT NOT NULL,
  PRIMARY KEY (`idPrivilege`, `idEmploye`),
  INDEX `fk_Privilege_has_Employe_Employe1_idx` (`idEmploye` ASC) VISIBLE,
  INDEX `fk_Privilege_has_Employe_Privilege1_idx` (`idPrivilege` ASC) VISIBLE,
  CONSTRAINT `fk_Privilege_has_Employe_Privilege1`
    FOREIGN KEY (`idPrivilege`)
    REFERENCES `goodfood`.`Privilege` (`idPrivilege`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Privilege_has_Employe_Employe1`
    FOREIGN KEY (`idEmploye`)
    REFERENCES `goodfood`.`Employe` (`idEmploye`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Regroupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Regroupe` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Regroupe` (
  `idPrivilegeParent` INT NOT NULL,
  `idPrivilegeEnfant` INT NOT NULL,
  PRIMARY KEY (`idPrivilegeParent`, `idPrivilegeEnfant`),
  INDEX `fk_Privilege_has_Privilege_Privilege2_idx` (`idPrivilegeEnfant` ASC) VISIBLE,
  INDEX `fk_Privilege_has_Privilege_Privilege1_idx` (`idPrivilegeParent` ASC) VISIBLE,
  CONSTRAINT `fk_Privilege_has_Privilege_Privilege1`
    FOREIGN KEY (`idPrivilegeParent`)
    REFERENCES `goodfood`.`Privilege` (`idPrivilege`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Privilege_has_Privilege_Privilege2`
    FOREIGN KEY (`idPrivilegeEnfant`)
    REFERENCES `goodfood`.`Privilege` (`idPrivilege`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Localisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Localisation` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Localisation` (
  `idAdresse` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  PRIMARY KEY (`idAdresse`, `idUtilisateur`),
  INDEX `fk_Adresse_has_Utilisateur_Utilisateur1_idx` (`idUtilisateur` ASC) VISIBLE,
  INDEX `fk_Adresse_has_Utilisateur_Adresse1_idx` (`idAdresse` ASC) VISIBLE,
  CONSTRAINT `fk_Adresse_has_Utilisateur_Adresse1`
    FOREIGN KEY (`idAdresse`)
    REFERENCES `goodfood`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Adresse_has_Utilisateur_Utilisateur1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `goodfood`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goodfood`.`Categorise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goodfood`.`Categorise` ;

CREATE TABLE IF NOT EXISTS `goodfood`.`Categorise` (
  `idProduit` INT NOT NULL,
  `idCategorie` INT NOT NULL,
  PRIMARY KEY (`idProduit`, `idCategorie`),
  INDEX `fk_Produit_has_Categorie_Categorie1_idx` (`idCategorie` ASC) VISIBLE,
  INDEX `fk_Produit_has_Categorie_Produit1_idx` (`idProduit` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_has_Categorie_Produit1`
    FOREIGN KEY (`idProduit`)
    REFERENCES `goodfood`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_has_Categorie_Categorie1`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `goodfood`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
