name: Workflow GoodFood
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04 ]
    steps:
      - name: Install docker
        uses: docker
      - name: Install Node
        uses: node
        with:
          node-version: 12.x
      - name: Verify install
        run: node -v && docker -v
