name: GoodFood CI

on: [push]

jobs:
  init:
    runs-on: ubuntu-18.04
    name: Init
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop

      - name: Setup Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'goodfood'
          mysql user: 'goodfood'
          mysql password: 'goodfood'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install node dependencies
        run: npm i

      - name: Install app dependencies
        run: cd ./app/good-food && npm i

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

  build:
    runs-on: ubuntu-18.04
    name: Build
    needs: init
    steps:     

   
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: logs
        run: ls

      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop

      - name: Setup Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'goodfood'
          mysql user: 'goodfood'
          mysql password: 'goodfood'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install node dependencies
        run: npm i

      - name: Install app dependencies
        run: cd ./app/good-food && npm i

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Restore project
        run: cd ./api/auth && dotnet restore

      - name: Maven Package
        run: cd ./api/data && mvn clean package -DskipTests

      - name: Maven Verify
        run: cd ./api/data && mvn clean verify -DskipTests

      - name: Build C# API
        run: cd ./api/auth && dotnet build

      - name: Build Java API
        run: cd ./api/data && mvn spring-boot:start

      - name: Build Angular app
        run: cd ./app/good-food && npm run build


  test_java:
    runs-on: ubuntu-18.04
    name: Test Java
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop

      - name: Setup Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'goodfood'
          mysql user: 'goodfood'
          mysql password: 'goodfood'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install node dependencies
        run: npm i

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Test JAVA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_JAVA_TOKEN }}
        run : cd ./api/data && mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

  test_dotnet:
    runs-on: windows-latest
    name: Tests C#
    needs: build
    steps:
      - name: Test directory
        run: dir
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~api\auth\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\api\auth\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\api\auth\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\api\auth\.sonar\scanner
          dir .\api\auth
          dir .\api\auth\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_CSHARP_TOKEN: ${{ secrets.SONAR_CSHARP_TOKEN }}
        shell: powershell
        run: |
          .\api\auth\.sonar\scanner\dotnet-sonarscanner begin /k:"goodfood-csharp" /o:"cesi-plasc" /d:sonar.login="${{ secrets.SONAR_CSHARP_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          cd .\api\auth
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_CSHARP_TOKEN }}"

  test_angular:
    runs-on: ubuntu-18.04
    name: Tests Angular
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install node dependencies
        run: npm i

      - name: Install app dependencies
        run: cd ./app/good-food && npm i

      - name: Test Angular
        run: cd ./app/good-food && npm run test:ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_ANGULAR_TOKEN }}

