name: GoodFood CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop

      - name: Setup Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'goodfood'
          mysql root password: 'goodfood'
          mysql user: 'goodfood'
          mysql password: 'goodfood'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install node dependencies
        run: npm i

      - name: Install app dependencies
        run: cd ./app/good-food && npm i

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Restore project
        run: cd ./api/auth && dotnet restore

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Maven Package
        run: cd ./api/data && mvn clean package -DskipTests

      - name: Maven Verify
        run: cd ./api/data && mvn clean verify -DskipTests

      - name: Build C# API
        run: cd ./api/auth && dotnet build

      - name: Build Java API
        run: cd ./api/data && ./mvnw spring-boot:build-image

      - name: Build Angular app
        run: cd ./app-good-food && npm run build
