name: GoodFood CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Setup Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          container name: 'goodfood-db'
          host port: 3306
          container port: 3306
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql database: 'goodfood'
          mysql root password: 'root'
          mysql user: 'goodfood'
          mysql password: 'goodfood'
      - run: docker container ls
